name: Build and publish dist (Hostinger layout)

on:
  push:
    branches: [ main ]

# 👇 Necessário para poder fazer git push no próprio repositório
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Detecta gerenciador de pacotes e instala deps
      - name: Install deps (npm/yarn/pnpm)
        run: |
          set -e
          if [ -f pnpm-lock.yaml ]; then
            echo "Using pnpm"
            corepack enable
            pnpm install --frozen-lockfile
            echo "BUILD_CMD=pnpm run build" >> $GITHUB_ENV
          elif [ -f yarn.lock ]; then
            echo "Using yarn"
            corepack enable
            yarn install --frozen-lockfile
            echo "BUILD_CMD=yarn build" >> $GITHUB_ENV
          else
            echo "Using npm"
            (npm ci || npm install)
            echo "BUILD_CMD=npm run build" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          set -e
          echo "Running: $BUILD_CMD"
          eval "$BUILD_CMD"

      # Reorganiza a saída para o layout da Hostinger
      - name: Reshape dist to Hostinger layout
        run: |
          set -e
          mkdir -p dist/assets dist/images dist/src/content/posts

          # Move quaisquer .css/.js/.map soltos p/ dist/assets
          find dist -maxdepth 2 -type f \( -name "*.css" -o -name "*.js" -o -name "*.map" \) -not -path "dist/assets/*" -exec mv -f {} dist/assets/ \; || true

          # Copia ícones/arquivos de public (exceto index.html)
          if [ -d public ]; then
            shopt -s nullglob
            for f in public/*; do
              if [ -f "$f" ] && [ "$(basename "$f")" != "index.html" ]; then
                cp -f "$f" dist/
              fi
            done
            shopt -u nullglob
          fi

          # Imagens → dist/images
          if [ -d public/images ]; then
            cp -R public/images/* dist/images/ 2>/dev/null || true
          fi
          if [ -d images ]; then
            cp -R images/* dist/images/ 2>/dev/null || true
          fi

          # MDX → dist/src/content/posts
          if [ -d src/content/posts ]; then
            cp -R src/content/posts/* dist/src/content/posts/ 2>/dev/null || true
          fi

          # .htaccess → raiz do deploy
          if [ -f .htaccess ]; then
            cp -f .htaccess dist/.htaccess
          elif [ -f config/.htaccess ]; then
            cp -f config/.htaccess dist/.htaccess
          else
            echo "WARNING: .htaccess não encontrado no repo; rotas de SPA podem quebrar."
          fi

      # 👇 Usa o GITHUB_TOKEN para autenticar o push no branch deploy
      - name: Push dist to deploy branch
        env:
          REPO: ManyRagDev/brincar-com-prop
          BRANCH: deploy
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          cd dist
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy"
          git branch -M "$BRANCH"
          git remote add origin "https://x-access-token:${TOKEN}@github.com/${REPO}.git"
          git push -f origin "$BRANCH"
