name: Build and publish dist (Hostinger layout)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      # Reorganiza a saída para o layout da Hostinger
      - name: Reshape dist to Hostinger layout
        run: |
          mkdir -p dist/assets dist/images dist/src/content/posts

          # Move quaisquer .css/.js/.map soltos p/ dist/assets
          find dist -maxdepth 2 -type f \( -name "*.css" -o -name "*.js" -o -name "*.map" \) -not -path "dist/assets/*" -exec mv -f {} dist/assets/ \; || true

          # Copia ícones/arquivos de public (exceto index.html)
          if [ -d public ]; then
            shopt -s nullglob
            for f in public/*; do
              if [ -f "$f" ] && [ "$(basename "$f")" != "index.html" ]; then
                cp -f "$f" dist/
              fi
            done
            shopt -u nullglob
          fi

          # Imagens → dist/images
          if [ -d public/images ]; then
            cp -R public/images/* dist/images/ 2>/dev/null || true
          fi
          if [ -d images ]; then
            cp -R images/* dist/images/ 2>/dev/null || true
          fi

          # MDX → dist/src/content/posts
          if [ -d src/content/posts ]; then
            cp -R src/content/posts/* dist/src/content/posts/ 2>/dev/null || true
          fi

          # .htaccess → raiz do deploy (dist/.htaccess)
          if [ -f .htaccess ]; then
            cp -f .htaccess dist/.htaccess
          elif [ -f config/.htaccess ]; then
            cp -f config/.htaccess dist/.htaccess
          else
            echo "WARNING: .htaccess não encontrado no repo; rotas de SPA podem quebrar."
          fi

      - name: Push dist to deploy branch
        run: |
          cd dist
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy"
          git branch -M deploy
          git remote add origin https://github.com/ManyRagDev/brincar-com-prop.git
          git push -f origin deploy
