name: Build and publish dist (Hostinger via FTP)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Detecta gerenciador de pacotes e instala deps
      - name: Install deps (npm/yarn/pnpm)
        run: |
          set -e
          if [ -f pnpm-lock.yaml ]; then
            echo "Using pnpm"
            corepack enable
            pnpm install --frozen-lockfile
            echo "BUILD_CMD=pnpm run build" >> $GITHUB_ENV
          elif [ -f yarn.lock ]; then
            echo "Using yarn"
            corepack enable
            yarn install --frozen-lockfile
            echo "BUILD_CMD=yarn build" >> $GITHUB_ENV
          else
            echo "Using npm"
            (npm ci || npm install)
            echo "BUILD_CMD=npm run build" >> $GITHUB_ENV
          fi

      # ✅ Corrige diferença de maiúsculas/minúsculas no Linux do Actions
      - name: Compat: espelhar 'src/content/Produtos' -> 'src/content/produtos' (case fix)
        run: |
          if [ -d src/content/Produtos ]; then
            rm -rf src/content/produtos
            mkdir -p src/content/produtos
            cp -R src/content/Produtos/* src/content/produtos/
            echo "Espelhado: src/content/Produtos -> src/content/produtos"
          else
            echo "Aviso: 'src/content/Produtos' não existe; nada a espelhar."
          fi

      - name: Build
        run: |
          echo "Running: $BUILD_CMD"
          eval "$BUILD_CMD"

      # Reorganiza a saída para o layout da Hostinger
      - name: Reshape dist to Hostinger layout
        run: |
          set -e
          mkdir -p dist/assets dist/images dist/src/content/posts dist/src/content/produtos

          # Move quaisquer .css/.js/.map soltos p/ dist/assets
          find dist -maxdepth 2 -type f \( -name "*.css" -o -name "*.js" -o -name "*.map" \) -not -path "dist/assets/*" -exec mv -f {} dist/assets/ \; || true

          # Copia ícones/arquivos de public (exceto index.html)
          if [ -d public ]; then
            shopt -s nullglob
            for f in public/*; do
              if [ -f "$f" ] && [ "$(basename "$f")" != "index.html" ]; then
                cp -f "$f" dist/
              fi
            done
            shopt -u nullglob
          fi

          # Imagens → dist/images
          if [ -d public/images ]; then
            cp -R public/images/* dist/images/ 2>/dev/null || true
          fi
          if [ -d images ]; then
            cp -R images/* dist/images/ 2>/dev/null || true
          fi

          # MDX (posts do blog) → dist/src/content/posts
          if [ -d src/content/posts ]; then
            cp -R src/content/posts/* dist/src/content/posts/ 2>/dev/null || true
          fi

          # JSON (produtos da loja) → dist/src/content/produtos
          # (mantemos por garantia; o import.meta.glob já terá embutido no bundle)
          if [ -d src/content/produtos ]; then
            cp -R src/content/produtos/* dist/src/content/produtos/ 2>/dev/null || true
          fi

          # .htaccess → raiz do deploy
          if [ -f .htaccess ]; then
            cp -f .htaccess dist/.htaccess
          elif [ -f config/.htaccess ]; then
            cp -f config/.htaccess dist/.htaccess
          else
            echo "WARNING: .htaccess não encontrado no repo; rotas de SPA podem quebrar."
          fi

          # Copiar auxiliares (landing pages) → vira lp no servidor
          if [ -d auxiliares ]; then
            rm -rf dist/lp
            cp -R auxiliares dist/lp
          fi

      # 🔹 Cria arquivo version.txt com commit e data
      - name: Write version file
        run: |
          echo "commit: $GITHUB_SHA" > dist/version.txt
          echo "date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> dist/version.txt

      # 🔹 Debug: listar arquivos relevantes do dist
      - name: Debug dist contents
        run: |
          echo ">>> JSONs que foram para o bundle (cópia de segurança no dist/):"
          ls -al dist/src/content/produtos || true

      # 🔹 Deploy automático via FTP para Hostinger (incremental)
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftp
          port: 21
          local-dir: ./dist/
          server-dir: ./
          exclude: |
            **/.git*
            **/node_modules/**
